### ISSUE TITLE
Open and scroll, modal doesn't stay put

### ISSUE THREAD

**Issue by Braunson** [digaev/jQuery-timeDurationPicker#1]
When you open the duration picker and scroll on the page, it scrolls with away from the element. Ideally it would be nice to have it stay with the element i.e. not fixed but positioned absolute.

**Comment by digaev** [comment]
I [added](https://github.com/digaev/jQuery-timeDurationPicker/commit/a12b2664baf99eac43bad93e54c88eb30c680756) `position` option (it is `fixed` by default), so now you can set it manually on initialization. Something like that:

``` js
$('#duration').timeDurationPicker({ position: 'absolute' });
```

Thank for the PR.
