### ISSUE TITLE
How to set duration from outside the widget

### ISSUE THREAD

**Issue by devrazn** [digaev/jQuery-timeDurationPicker#11]
Can anyone help me setting the duration from outside the widget. I didn't find that in the documentation. I also looked into the source code and saw there is setDuration() function but couldn't find how to use it in documentation. Also I'm not sure if it performs the function I'm looking for.

**Comment by digaev** [comment]
[You can access the widget from outside the same way just like any other jQuery widget](https://stackoverflow.com/questions/8506621/accessing-widget-instance-from-outside-widget). So what you can do is something like this:
```js
const picker = $('#widget').timeDurationPicker('instance');

picker.setDuration('PT3H25M45S');
picker._save();
console.log(picker.translate());
```

**Comment by devrazn** [comment]
> [You can access the widget from outside the same way just like any other jQuery widget](https://stackoverflow.com/questions/8506621/accessing-widget-instance-from-outside-widget). So what you can do is something like this:
> 
> ```js
> const picker = $('#widget').timeDurationPicker('instance');
> 
> picker.setDuration('PT3H25M45S');
> picker._save();
> console.log(picker.translate());
> ```

Thanks. This does help me achieve what I wanted to do. It would be best if you can include this in the documentation as well. It would surely help a lot of other developers facing the same issue as me.
