### ISSUE TITLE
Can you show me example on how to set css  for window/button using css settings.

### ISSUE THREAD

**Issue by sarojekka** [digaev/jQuery-timeDurationPicker#6]

**Comment by sarojekka** [comment]
Readme information does not show an example for CSS.
Can I use anchor tag instead on text for showing resulted text so that it looks clickable?

**Comment by digaev** [comment]
You can set CSS (of the widget's main div) on initialization like this:
```js
$('#duration').timeDurationPicker({
  css: {
    color: 'red'
  }
});
```
Or, you can you do it by adding css to you page:
```css
.time-duration-picker-content {
  color: 'red';
}
```
