### ISSUE TITLE
can we not use jquery-datepicker transalations?

### ISSUE THREAD

**Issue by sarojekka** [digaev/jQuery-timeDurationPicker#7]

**Comment by sarojekka** [comment]
can you provide transalation js too?

**Comment by digaev** [comment]
There is only one translation which comes with plugin, it's English:
https://github.com/digaev/jquery-time-duration-picker/blob/0c04182b4803dd5726ced844f3614006e0f0a26e/src/jquery-time-duration-picker.js#L33

If you want to add any other language you should translate it by yourself (according to [plural rules](https://www.unicode.org/cldr/charts/latest/supplemental/language_plural_rules.html) of desired language).

Here is example of Russian translation: https://gist.github.com/digaev/e7d92abad1d410372189711f94369237

HTML:
```HTML
<!-- First include plugin -->
<script src="jquery-time-duration-picker.js"></script>

<!-- Then include translation file -->
<script src="jquery-time-duration-picker_ru.js"></script>

<!-- And initialize widget -->
<script>
 // Set global options
$.timeDurationPicker.defaults({ lang: 'ru_RU' });

// Or set it for each widget
$('#duration').timeDurationPicker({ lang: 'ru_RU' });
</script>
```
