### ISSUE TITLE
Ability to return and parse ISO 8601 durations from duration picker

### ISSUE THREAD

**Issue by DCRGraphs** [digaev/jQuery-timeDurationPicker#8]
Would it be possible to parse ISO 8601 duration format, check out https://en.wikipedia.org/wiki/ISO_8601#Durations for details? I.e. format P[n]Y[n]M[n]DT[n]H[n]M[n]S to represent a duration instead of number of seconds since January 1st 1970 - which seems a bit odd :-)

We would like to contribute to this duration picker by adding this functionality if ok with you.

**Comment by digaev** [comment]
Well, sounds cool. It would be nice if you can keep backward compatibility (i.e methods `setSeconds` & `getSeconds` set/get `Integer` currently), or implement similar methods instead, but it's not super important, anyways will see what are you going to do.

**Comment by DCRGraphs** [comment]
Would it be something you would be interested implemented - obviously you will be compensated for it but we will still share the component here as open source. If so - please email me.

**Comment by digaev** [comment]
Not sure where I can find your email, lets make it a bit more clearly, as I understand you want me to add to the widget two methods:

1.
```
function setDuration(duration) {
}
```
Where `duration` is a `String` in `P[n]Y[n]M[n]DT[n]H[n]M[n]S` format.

2.
```
// The method name already reserved for internal usage, but I can replace it
function getDuration() {
}
```
Returns `String` in `P[n]Y[n]M[n]DT[n]H[n]M[n]S` format ?

**Comment by DCRGraphs** [comment]
Yes. Exactly. If you read the ISO 8601 specification you will find that a duration has a few other formats - but the P[n]y... is the dominant one. But, we should probably be able to parse all the formats.

We will also do localization into 5-6 languages and I hope it is ok we add these to the code too. I prefer have everything in one place.

**Comment by digaev** [comment]
I don't have an linked account, could you just post the email here? I'll delete it asap, or email me ffs.cmp@gmail.com, I'll respond you in day or two, probably with some results.
